print('Welcome to the Mad Lib Generator!')
#gather inputs
adjective1 = raw_input('Type in an adjective: ')
adjective2 = raw_input('Type in an adjective: ')
adjective3 = raw_input('Type in an adjective: ')
adjective4 = raw_input('Type in an adjective: ')
animals = raw_input('Type in a plural animal: ')
verb1 = raw_input('Type in a verb: ')
plural_noun = raw_input('Type in a plural noun: ')
woman_musician = raw_input('Type in the name of a woman musician: ')
beverage = raw_input('Type in a beverage: ')
body_part = raw_input('Type in a plural body part: ')


#tell story
print(' ')
print("Excellent choices! Here's your story...")
print('--------------------------------')
print('There once was a ' + adjective1 + ' programmer named' + woman_musician)
print('who wanted to build a ' + adjective2 + ' mobile app to')
print('help ' + adjective3 + ' ' + animals + ' find new homes.')
print(' ')
print(woman_musician + ' stayed up all night, drinking lots of')
print('caffeinated ' + beverage + ' as she worked and worked')
print('trying to complete her ' + adjective4 + ' program.')
print(' ')
print('Whenever Ani hit a dead end, she would')
print('exclaim "' + plural_noun + '"!')
print(' ')
print('But she was not discouraged, and after a quick break')
print('to ' + verb1 + ' and clear her head, she got back to work.')
print(' ')
print('By morning, when the sun started to rise, she let out a')
print('big yawn and stretched her ' + body_part + '.')
print('Finally, she was done.')
print('--------------------------------')
